### ISSUE TITLE
URL Shortener links use HTTP by default even though the current protocol is HTTPS

### ISSUE THREAD

**Issue by Bloeckchengrafik** [ThnksCJ/URL-Shortener#1]

**Comment by ThnksCJ** [comment]
This one is done so you can have either Https or http depending on what you want

**Comment by Bloeckchengrafik** [comment]
![grafik](https://user-images.githubusercontent.com/37768199/198898105-c4c28475-793d-4ac4-b634-1cd704dd50b5.png)
I think, this is the problem

https://github.com/ThnksCJ/URL-Shortener/blob/master/app.js#L53

**Comment by ThnksCJ** [comment]
Ahh, I misunderstood your issue. Ye I can fix that when I get home

**Comment by ThnksCJ** [comment]
Fixed in newest commit
